var searchData=
[
  ['raii',['RAII',['../struct_tempus_1_1_r_a_i_i.html',1,'Tempus']]],
  ['remove_5fconst',['remove_const',['../struct_tempus_1_1remove__const.html',1,'Tempus']]],
  ['remove_5fconst_3c_20t_20const_20_20_3e',['remove_const&lt; T const  &gt;',['../struct_tempus_1_1remove__const_3_01_t_01const_01_01_4.html',1,'Tempus']]],
  ['request',['Request',['../class_tempus_1_1_request.html',1,'Tempus']]],
  ['restriction',['Restriction',['../class_tempus_1_1_road_1_1_restriction.html',1,'Tempus::Road']]],
  ['restrictions',['Restrictions',['../class_tempus_1_1_road_1_1_restrictions.html',1,'Tempus::Road']]],
  ['result',['Result',['../class_db_1_1_result.html',1,'Db']]],
  ['resultelement',['ResultElement',['../class_tempus_1_1_result_element.html',1,'Tempus']]],
  ['resultiterator',['ResultIterator',['../class_db_1_1_result_iterator.html',1,'Db']]],
  ['reversegraph',['ReverseGraph',['../struct_tempus_1_1_multimodal_1_1_reverse_graph.html',1,'Tempus::Multimodal']]],
  ['reversegrapht',['ReverseGraphT',['../class_tempus_1_1_reverse_graph_t.html',1,'Tempus']]],
  ['reversegrapht_3c_20road_3a_3agraph_2c_20road_3a_3anode_2c_20road_3a_3asection_20_3e',['ReverseGraphT&lt; Road::Graph, Road::Node, Road::Section &gt;',['../class_tempus_1_1_reverse_graph_t.html',1,'Tempus']]],
  ['road2poi_5ft',['road2poi_t',['../struct_tempus_1_1_multimodal_1_1_edge_1_1road2poi__t.html',1,'Tempus::Multimodal::Edge']]],
  ['road2road_5ft',['road2road_t',['../struct_tempus_1_1_multimodal_1_1_edge_1_1road2road__t.html',1,'Tempus::Multimodal::Edge']]],
  ['road_5ft',['road_t',['../struct_tempus_1_1_multimodal_1_1_vertex_1_1road__t.html',1,'Tempus::Multimodal::Vertex']]],
  ['roadedgepair',['RoadEdgePair',['../struct_tempus_1_1_road_edge_pair.html',1,'Tempus']]],
  ['roadedgespeedprofile',['RoadEdgeSpeedProfile',['../class_tempus_1_1_road_edge_speed_profile.html',1,'Tempus']]],
  ['roadmap',['Roadmap',['../class_tempus_1_1_roadmap.html',1,'Tempus']]],
  ['roadplugin',['RoadPlugin',['../class_tempus_1_1_road_plugin.html',1,'Tempus']]],
  ['roadpluginrequest',['RoadPluginRequest',['../class_tempus_1_1_road_plugin_request.html',1,'Tempus']]],
  ['roadstep',['RoadStep',['../struct_tempus_1_1_roadmap_1_1_road_step.html',1,'Tempus::Roadmap']]],
  ['routingdata',['RoutingData',['../class_tempus_1_1_routing_data.html',1,'Tempus']]],
  ['routingdatabuilder',['RoutingDataBuilder',['../class_tempus_1_1_routing_data_builder.html',1,'Tempus']]],
  ['routingdatabuilderregistry',['RoutingDataBuilderRegistry',['../class_tempus_1_1_routing_data_builder_registry.html',1,'Tempus']]],
  ['rowvalue',['RowValue',['../class_db_1_1_row_value.html',1,'Db']]]
];
