#! /bin/sh -e

test -x /usr/local/bin/wps || exit 0

status () {
        if [ -z "$(ps h -C /usr/local/bin/wps -U daemon)" ];
        then
            echo "wps is not running"
        else
            echo "wps is running"
        fi
}

start () {
        if [ -z "$(ps h -C /usr/local/bin/wps -U daemon)" ];
        then
            echo "Starting wps Daemon"
            su daemon -c "TEMPUS_DATA_DIRECTORY=/usr/local/share/tempus/data /usr/local/bin/wps -D -c /usr/local/lib -p 9000 -l forbidden_movements_plugin -l sample_multi_plugin -l sample_pt_plugin -l sample_road_plugin -t 4"
        else
            echo "wps is already running"
        fi
}

stop () {
        if [ -z "$(ps h -C /usr/local/bin/wps -U daemon)" ];
        then
            echo "wps is not running"
        else
            echo "Stopping wps Daemon"
            killall --user daemon wps
        fi
}

case "$1" in
    start|stop)
        ${1}
        ;;

    restart|reload|force-reload)
        stop 
        start
        ;;

    force-stop)
        stop
        killall -q wps || true
        sleep 2
        killall -q -9 wps || true
        ;;

    status)
        status
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|force-stop|restart|reload|force-reload|status}"
        exit 1
        ;;
esac
exit 0
